### ISSUE TITLE
Error when embedding fewer than 5 tokens

### ISSUE THREAD

**Issue by HowieG** [sdan/vlite#9]
Tokenizer: BertTokenizerFast(name_or_path='sentence-transformers/all-MiniLM-L6-v2', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True)
MPS is available
Device: mps
Encoded input done torch.Size([1, 21])
Encoded input moved to device
MPS is available
Device: mps
Encoded input done torch.Size([1, 12])
Encoded input moved to device
[remember] Sims: (1, 1)
Traceback (most recent call last):
  File "/Users/howardgil/Desktop/Projects/vlite/vlite/Howie.py", line 11, in <module>
    vlite.remember(text="What type of pizza should I get, Howie?")
  File "/Users/howardgil/Desktop/Projects/vlite/vlite/main.py", line 59, in remember
    top_5_idx = np.argpartition(sims, -top_k)[-top_k:]
  File "/usr/local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 858, in argpartition
    return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
  File "/usr/local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
ValueError: kth(=-4) out of bounds (1)

vlite always returns the top 5 most similar matches, so index out of bounds error when less than 5 tokens embedded. Number of similar matches returned should be dynamic

**Comment by HowieG** [comment]
Correction, remember takes a number top_k which defaults to 5 so it is dynamic. Just need to account for the case where # similarities < top_k which can be often
